invoice/urls.py
<<<<<<< HEAD
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView, createInvoice, view_PDF,get_details_customer,get_product_rate,create_recovery,recovery_list,generate_invoice_excel_report,generate_shop_excel_report,generate_recoveries_excel_report,delete_invoice,editInvoice,edit_recovery,delete_recovery

app_name = 'invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name="invoice-list"),
    path('invoice/create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice-delete/<id>', delete_invoice, name='invoice-delete'),
    path('invoice-edit/<id>', editInvoice, name='invoice-edit'),
    # path('invoice-download/<id>', generate_PDF, name='invoice-download'),
    path('create-recovery/<id>', create_recovery, name='create-recovery'),
    path('recovery-list/',recovery_list, name='recovery-list'),
    path('edit_recovery/<int:pk>/', edit_recovery, name='edit_recovery'),
    path('delete_recovery/<int:pk>/', delete_recovery, name='delete_recovery'),
    path('get-customer-details/<str:shop_name>/', get_details_customer, name='get_customer_details'),
    path('get-product-rate/<str:product_name>/', get_product_rate, name='get_product_rate'),
    path('gen-report-invoice/', generate_invoice_excel_report, name='generate_invoice_report'),
    path('gen-report-shops/', generate_shop_excel_report, name='generate_shops_report'),
    path('gen-report-recovery/', generate_recoveries_excel_report, name='generate_recovery_report'),


]
=======
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView, createInvoice, view_PDF,get_details_customer,get_product_rate,create_recovery

app_name = 'invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name="invoice-list"),
    path('invoice/create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    # path('invoice-download/<id>', generate_PDF, name='invoice-download'),
    path('create-recovery/<id>', create_recovery, name='create-recovery'),
    path('get-customer-details/<str:shop_name>/', get_details_customer, name='get_customer_details'),
    path('get-product-rate/<str:product_name>/', get_product_rate, name='get_product_rate'),
]
>>>>>>> origin/main

myapp/urls.py
<<<<<<< HEAD
from django.urls import path
from . import views



urlpatterns = [
    # path('', views.index, name='index'),

    path('managers/', views.managers, name='managers'),
    path('add-manager/', views.add_manager, name='add_manager'),
    path('edit-manager/<int:manager_id>/', views.edit_manager, name='edit_manager'),
    path('delete-manager/<int:manager_id>/', views.delete_manager, name='delete_manager'),
    
    path('shops/', views.shop_list, name='shop_list'),
    path('add_shop/', views.add_shop, name='add_shop'),
    path('edit_shop/<int:pk>/', views.edit_shop, name='edit_shop'),
    path('delete_shop/<int:pk>/', views.delete_shop, name='delete_shop'),

    path('products/', views.product_list, name='product_list'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:pk>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:pk>/', views.delete_product, name='delete_product'),

    path('days/', views.days_list, name='days'),
    path('add_days/', views.add_day, name='add_days'),
    path('edit_day/<int:pk>/', views.edit_day, name='edit_day'),
    path('delete_day/<int:pk>/', views.delete_day, name='delete_day'),

    path('sales_persons/', views.sales_person_list, name='sales_person_list'),
    path('add_sales_person/', views.add_sales_person, name='add_sales_person'),
    path('edit_sales_person/<int:pk>/', views.edit_sales_person, name='edit_sales_person'),
    path('delete_sales_person/<int:pk>/', views.delete_sales_person, name='delete_sales_person'),

    path('routes/', views.route_list, name='route_list'),
    path('add_route/', views.add_route, name='add_route'),
    path('edit_route/<int:pk>/', views.edit_route, name='edit_route'),
    path('delete_route/<int:pk>/', views.delete_route, name='delete_route'),

    path('routings/', views.routing_list, name='routing_list'),
    path('add_routing/', views.routing_create, name='add_routing'),
    path('edit_routing/<int:pk>/', views.edit_routing, name='edit_routing'),
    path('delete_routing/<int:pk>/', views.routing_delete, name='delete_routing'),

    path('claims/', views.claims_list, name='claim_list'),
    path('add_claim/', views.claim_create, name='add_claim'),
    path('edit_claim/<int:pk>/', views.edit_claim, name='edit_claim'),
    path('delete_claim/<int:pk>/', views.claim_delete, name='delete_claim'),

    path('transactions/', views.transaction_list, name='transaction_list'),
    path('delete_transactions/<int:transaction_id>/', views.delete_transaction, name='delete_transaction'),

=======
from django.urls import path
from . import views



urlpatterns = [
    # path('', views.index, name='index'),

    path('managers/', views.managers, name='managers'),
    path('add-manager/', views.add_manager, name='add_manager'),
    path('edit-manager/<int:manager_id>/', views.edit_manager, name='edit_manager'),
    path('delete-manager/<int:manager_id>/', views.delete_manager, name='delete_manager'),
    
    path('shops/', views.shop_list, name='shop_list'),
    path('add_shop/', views.add_shop, name='add_shop'),
    path('edit_shop/<int:pk>/', views.edit_shop, name='edit_shop'),
    path('delete_shop/<int:pk>/', views.delete_shop, name='delete_shop'),

    path('products/', views.product_list, name='product_list'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:pk>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:pk>/', views.delete_product, name='delete_product'),

    path('days/', views.days_list, name='days'),
    path('add_days/', views.add_day, name='add_days'),
    path('edit_day/<int:pk>/', views.edit_day, name='edit_day'),
    path('delete_day/<int:pk>/', views.delete_day, name='delete_day'),

    path('sales_persons/', views.sales_person_list, name='sales_person_list'),
    path('add_sales_person/', views.add_sales_person, name='add_sales_person'),
    path('edit_sales_person/<int:pk>/', views.edit_sales_person, name='edit_sales_person'),
    path('delete_sales_person/<int:pk>/', views.delete_sales_person, name='delete_sales_person'),

    path('routes/', views.route_list, name='route_list'),
    path('add_route/', views.add_route, name='add_route'),
    path('edit_route/<int:pk>/', views.edit_route, name='edit_route'),
    path('delete_route/<int:pk>/', views.delete_route, name='delete_route'),

    path('routings/', views.routing_list, name='routing_list'),
    path('add_routing/', views.routing_create, name='add_routing'),
    path('edit_routing/<int:pk>/', views.edit_routing, name='edit_routing'),
    path('delete_routing/<int:pk>/', views.routing_delete, name='delete_routing'),

    path('claims/', views.claims_list, name='claim_list'),
    path('add_claim/', views.claim_create, name='add_claim'),
    path('edit_claim/<int:pk>/', views.edit_claim, name='edit_claim'),
    path('delete_claim/<int:pk>/', views.claim_delete, name='delete_claim'),

    path('transactions/', views.transaction_list, name='transaction_list'),
    path('delete_transactions/<int:transaction_id>/', views.delete_transaction, name='delete_transaction'),

>>>>>>> origin/main
]

mysite/urls.py
<<<<<<< HEAD
from django.contrib import admin
from django.urls import path, include 
from myapp.views import index
from userprofile.views import signup,LogoutView
from django.contrib.auth import views

urlpatterns = [
    path('', index,name="index"),    
    path('invoice/', include("invoice.urls")),
    path('myapp/', include("myapp.urls")),
    path('sign-up/',signup,name="signup"),
    # using django default (builtin) class base views and inherit the template
    path('log-in/',views.LoginView.as_view(template_name="userprofile/login.html"), name="login"),
    path("log-out/",LogoutView.as_view(),name="logout"),
    path('admin/', admin.site.urls),
]
=======
from django.contrib import admin
from django.urls import path, include 
from myapp.views import index
from userprofile.views import signup,LogoutView
from django.contrib.auth import views

urlpatterns = [
    path('', index,name="index"),    
    path('invoice/', include("invoice.urls")),
    path('myapp/', include("myapp.urls")),
    path('sign-up/',signup,name="signup"),
    # using django default (builtin) class base views and inherit the template
    path('log-in/',views.LoginView.as_view(template_name="userprofile/login.html"), name="login"),
    path("log-out/",LogoutView.as_view(),name="logout"),
    path('admin/', admin.site.urls),
]
>>>>>>> origin/main

invoice/models.py
<<<<<<< HEAD
from decimal import Decimal
from django.db import models
import datetime
# Create your models here.
class InvoiceManager(models.Manager):
    def search(self, search_query=None):
        if search_query:
            return self.get_queryset().filter(
                models.Q(customer__icontains=search_query) |
                models.Q(salesperson__icontains=search_query) |
                models.Q(manager__icontains=search_query) |
                models.Q(date__icontains=search_query)
            )
        else:
            return self.get_queryset()
    
class Invoice(models.Model):
    customer = models.CharField(max_length=100)
    customer_email = models.TextField(null=True, blank=True)
    billing_address = models.TextField(null=True, blank=True)
    date = models.DateField()
    due_date = models.DateField(null=True, blank=True)
    message = models.TextField(default= "this is a default message.")
    total_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    salesperson = models.CharField(max_length=100, blank=True, null=True)
    manager = models.CharField(max_length=100, blank=True, null=True)
    routing = models.CharField(max_length=255, blank=True, null=True)
    paid_amount=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    balance=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    previous_balance=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    # current_balance=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    sale_types = models.CharField(max_length=255, blank=True, null=True)
    status = models.BooleanField(default=False)

    objects = InvoiceManager()
    

    def save(self, *args, **kwargs):
        if isinstance(self.total_amount, str):
            self.total_amount = Decimal(self.total_amount)
        if isinstance(self.paid_amount, str):
            self.paid_amount = Decimal(self.paid_amount)

        # Calculate balance if both total_amount and paid_amount are not None
        if self.total_amount is not None and self.paid_amount is not None:
            self.balance = self.total_amount - self.paid_amount

        super().save(*args, **kwargs)



    def __str__(self):
        return str(self.customer)
    
    def get_status(self):
        return self.status
    
    
    

    # def save(self, *args, **kwargs):
        # if not self.id:             
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)

class LineItem(models.Model):
    customer = models.ForeignKey(Invoice,on_delete=models.CASCADE, blank=True, null=True)
    service = models.TextField()
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=9, decimal_places=2)
    amount = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return str(self.customer)
    

# Create your models here.
# class RecoveryManager(models.Manager):
#     def search(self, search_query=None):
#         if search_query:
#             return self.get_queryset().filter(
#                 models.Q(name__icontains=search_query) |
#                 models.Q(address__icontains=search_query) |
#                 models.Q(owner_number__icontains=search_query) |
#                 models.Q(owner_cnic__icontains=search_query)
#             )
#         else:
#             return self.get_queryset()
    
class Recovery(models.Model):
    customer_name = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    updated_date = models.DateField(auto_now=True)
    new_paid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    current_balance = models.DecimalField(max_digits=10, decimal_places=2)
    

        
    def __str__(self):
        return f"Recovery for {self.customer_name} on {self.date}"
=======
from decimal import Decimal
from django.db import models
import datetime
# Create your models here.
class Invoice(models.Model):
    customer = models.CharField(max_length=100)
    customer_email = models.TextField(null=True, blank=True)
    billing_address = models.TextField(null=True, blank=True)
    date = models.DateField()
    due_date = models.DateField(null=True, blank=True)
    message = models.TextField(default= "this is a default message.")
    total_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    salesperson = models.CharField(max_length=100, blank=True, null=True)
    manager = models.CharField(max_length=100, blank=True, null=True)
    routing = models.CharField(max_length=255, blank=True, null=True)
    paid_amount=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    balance=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    previous_balance=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    # current_balance=models.DecimalField(max_digits=9, decimal_places=2, default=0)
    sale_types = models.CharField(max_length=255, blank=True, null=True)
    status = models.BooleanField(default=False)
    

    def save(self, *args, **kwargs):
        if isinstance(self.total_amount, str):
            self.total_amount = Decimal(self.total_amount)
        if isinstance(self.paid_amount, str):
            self.paid_amount = Decimal(self.paid_amount)

        # Calculate balance if both total_amount and paid_amount are not None
        if self.total_amount is not None and self.paid_amount is not None:
            self.balance = self.total_amount - self.paid_amount

        super().save(*args, **kwargs)



    def __str__(self):
        return str(self.customer)
    
    def get_status(self):
        return self.status
    
    
    

    # def save(self, *args, **kwargs):
        # if not self.id:             
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)

class LineItem(models.Model):
    customer = models.ForeignKey(Invoice,on_delete=models.CASCADE, blank=True, null=True)
    service = models.TextField()
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=9, decimal_places=2)
    amount = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return str(self.customer)
    
class Recovery(models.Model):
    customer_name = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    updated_date = models.DateField(auto_now=True)
    new_paid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    current_balance = models.DecimalField(max_digits=10, decimal_places=2)
    

        
    def __str__(self):
        return f"Recovery for {self.customer_name} on {self.date}"
>>>>>>> origin/main
   

templates/invoice/Recovery_list.html
{% extends 'base.html' %}
{% comment %} {% block transactionsactive %} active {% endblock %} {% endcomment %}
{% block extra_head %} <style>
    /* Custom styling for first and last buttons */
    .paginate_button.first,
    .paginate_button.last {
        background-color: #b5f795; /* Change to your desired color */
        color: #fff; /* Change to your desired text color */
        border-color: #007bff; /* Change to your desired border color */
    }
</style>{% endblock %}
{% block content %}
<h6 class="card-title bg-success text-white center text-center py-3">View your Recoveries on daily basis </h6>
<div class="container-fluid mt-4 px-0">
    <!-- <form method="GET" action="{% url 'transaction_list' %}" class="mb-3"> -->
        <!-- <div class="form-row my-2">
        <div class="col">
            <label for="searchbyName"><b>Search by customer/Shop Name, salesperson, manager, or date (YYYY-MM-DD)</b></label>
            <input type="text" name="q" class="form-control" placeholder="Search by customer Name, salesperson, manager, or date (YYYY-MM-DD)" value="{{ request.GET.q }}">
        </div>
    </div>  -->
        <!-- <div class="form-row">
            <div class="col-auto">
                <label for="fromDate"><b>From</b></label>
                <input type="date" name="start_date" class="form-control" placeholder="Start Date" value="{{ request.GET.start_date }}">
            </div>
            <div class="col-auto">
                <label for="toDate"><b>To</b></label>
                <input type="date" name="end_date" class="form-control" placeholder="End Date" value="{{ request.GET.end_date }}">
            </div>
        </div>
        <div class="input-group">
            <button type="submit" class="btn btn-warning mt-2">Search</button>
        </div>
    </form> -->
    <!-- Table to display transactions data -->
    <div class="table-responsive">
        <table  id="recovery-table" class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Customer Name</th>
                    <th>Total Sale Amount</th>
                    <th>Order Date</th>
                    <th>Previous balance</th>
                    <th>Recovered Amount</th>
                    <th>Recovery Date</th>
                    <th>Current Balance</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for recovery in recoveryies_fetched %}
                <tr>
                    <td>{{recovery.id}}</td>
                    <td>{{ recovery.customer_name }}</td>
                    <td>{{ recovery.total_amount }}</td>
                    <td>{{ recovery.date }}</td>
                    <td>{{ recovery.balance }}</td>
                    <td>{{ recovery.new_paid_amount }}</td>
                    <td>{{ recovery.updated_date }}</td>
                    <td>{{ recovery.current_balance }}</td>
                    {% comment %} <td><a href="{% url 'invoice:edit_recovery' recovery.id %}" class="btn btn-sm btn-primary" disabled>Edit</a></td> {% endcomment %}
                    <td><a href="#" class="btn btn-sm btn-primary" disabled>Edit</a></td>
                    <td><a href="{% url 'invoice:delete_recovery' recovery.id %}" class="btn btn-sm btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
{% comment %} <script src="https://cdn.datatables.net/2.0.5/js/dataTables.min.js"></script> {% endcomment %}
<script>
    $(document).ready(function() {
        $('#recovery-table').DataTable({
            "pagingType": "full_numbers", // Use full pagination controls
            "pageLength": 3, // Show 10 entries per page
            "lengthMenu": [10, 25, 50, 75, 100], // Entries per page options
            "language": {
                "paginate": {
                    "previous": "«",
                    "next": "»"
                }
            }
        });
    });
</script>
{% endblock %}

templates/invoice/delete_invoice_confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
    <h2 style="color: blue;  margin-left:50px;">Delete Invoice</h2>
</div>
    <p style="margin:25px;">Are you sure you want to delete "{{ invoice.id }}"?</p>
    <form method="post">
        {% csrf_token %}

        <button type="submit" class="btn btn-success btn-block">Delete</button>
        <br>
    </form>
</div>
</div>
</div>
</div>
{% endblock %}

templates/invoice/invoice-list.html
<<<<<<< HEAD
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                    <h6 style="font-size:1.5rem">View Invoices/Transactions</h6>
                <div class="card-body">
                    <a href="{% url 'invoice:invoice-create' %}" class="btn btn-lg btn-primary  mb-3">Create Invoice/Transaction</a>
                    <div class="table-responsive">
                        <table id="invoicelist-table" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Invoice</th>
                                    <th>Customer</th>
                                    <th>Date</th>
                                    <th>Total Amount</th>
                                    <th>Total Paid</th>
                                    <th>Balance</th>
                                    <th>Previous Balance</th>
                                    <th>View</th>
                                    <th>Recovery</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for invoice in invoices %}
                                <tr>
                                    <td><input class="form-check-input" type="checkbox" value="{{ invoice.id }}" name="invoice_id" /></td>
                                    <td>#{{ invoice.id }}</td>
                                    <td>{{ invoice.customer }}</td>
                                    <td>{{ invoice.date }}</td>
                                    <td>{{ invoice.total_amount }}</td>
                                    <td>{{ invoice.paid_amount }}</td>
                                    <td>{{ invoice.balance }}</td>
                                    <td>{{ invoice.previous_balance }}</td>
                                    <td><a href="{% url 'invoice:invoice-detail' id=invoice.id %}" class="btn btn-sm btn-info">View</a></td>
                                    <td><a href="{% url 'invoice:create-recovery' id=invoice.id %}" class="btn btn-sm btn-success">Pay me</a></td> 
                                    <td><a href="{% url 'invoice:invoice-edit' id=invoice.id %}" class="btn btn-sm btn-primary">Edit</a></td> 
                                    <td><a href="{% url 'invoice:invoice-delete' id=invoice.id %}" class="btn btn-sm btn-danger">Delete</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_js %}
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#invoicelist-table').DataTable({
            "pagingType": "full_numbers", // Use full pagination controls
            "lengthMenu": [10, 25, 50, 75, 100], // Entries per page options
            "language": {
                "paginate": {
                    "previous": "«",
                    "next": "»"
                }
            }
        });
    });
</script>
{% endblock %}
=======
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <h1 class="card-title text-center"></h1>
            </div>
        </div>
    </div>
    <form action="{% url 'invoice:invoice-list' %}" method="post">{% csrf_token %}
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">All Orders / Change Order Status&nbsp;<button class="btn btn-info rounded">
                        <a href="{% url 'invoice:invoice-create' %}" class="text-white">Create Invoice</a>
                    </button></h5>
            </div>
            <div class="card-body">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Change Order Status</h5>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <select class="form-control rounded" id="status" name="status">
                                <option value="1">Paid</option>
                                <option value="0">Not Paid</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-info rounded" name="mybtn">Change Status</button>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>INVOICE</th>
                                        <th>CUSTOMER</th>
                                        <th>DATE</th>
                                        <th>TOTAL AMOUNT</th>
                                        <th>TOTAL PAID</th>
                                        <th>BALANCE</th>
                                        <th>Previous Balance</th>
                                        <th>View</th>
                                        <th>Recovery</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for invoice in invoices %}
                                    <tr>
                                        <td><input class="form-check-input" type="checkbox" value="{{ invoice.id }}" name="invoice_id" /></td>
                                        <td>#{{ invoice.id }}</td>
                                        <td>{{ invoice.customer }}</td>
                                        <td>{{ invoice.date }}</td>
                                        <td>{{ invoice.total_amount }}</td>
                                        <td>{{ invoice.paid_amount }}</td>
                                        <td>{{ invoice.balance }}</td>
                                        <td></td>
                                        <!-- <td>
                                            {% if invoice.get_status %}
                                            <span class="badge badge-success">Paid</span>
                                            {% else %}
                                            <span class="badge badge-warning">Not Paid</span>
                                            {% endif %}
                                        </td> -->
                                        <td><a href="{% url 'invoice:invoice-detail' id=invoice.id %}" class="btn btn-sm btn-info">View</a></td>
                                        <td><a href="{% url 'invoice:create-recovery' id=invoice.id %}" class="btn btn-sm btn-info">pay Please</a></td> 
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}







>>>>>>> origin/main

templates/invoice/recovery_form.html
<<<<<<< HEAD
{% extends 'base.html' %}

<!-- {% block daysactive %} active {% endblock daysactive %} -->

{% block content %}
<div class="container my-3">
    <h3>Recovery</h3>
    <form action={% url 'invoice:create-recovery' id=invoice_id %} method="post">{% csrf_token %}
  <div class="form-group">
    <label for="new_paid_amount">Recovered Amount</label>
    <input type="number" class="form-control" id="new_paid_amount" name='new_paid_amount' placeholder="Enter Recovered Amount here">
  </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</div>
{% endblock %}
=======
{% extends 'base.html' %}

<!-- {% block daysactive %} active {% endblock daysactive %} -->

{% block content %}
<div class="container my-3">
    <h3>Recovery</h3>
    <form action={% url 'invoice:create-recovery' id=invoice_id %} method="post">{% csrf_token %}
  <div class="form-group">
    <label for="new_paid_amount">Recovered Amount</label>
    <input type="number" class="form-control" id="new_paid_amount" name='new_paid_amount' placeholder="Enter Recovered Amount here">
  </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>



</div>
{% endblock %}
<!-- Include jQuery library
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

Your form
<form method="post" id="recoveryForm">
    {% csrf_token %}
    
    Display any form errors here if there are any 
    {{ form.non_field_errors }}
    
    <Prepopulate fields with data from the Invoice object 
    <label for="id_customer_name">Customer Name:</label>
    <input type="text" id="id_customer_name" name="customer_name" readonly>
    
    <label for="id_total_amount">Total Amount:</label>
    <input type="text" id="id_total_amount" name="total_amount" readonly>
    
    <label for="id_date">Date:</label>
    <input type="text" id="id_date" name="date" readonly>

    <label for="id_balance">Previous Balance:</label>
    <input type="text" id="id_balance" name="balance" readonly>
    
    Render the form fields 
    {{ form.new_paid_amount.label_tag }}
    {{ form.new_paid_amount }}
    {{ form.new_paid_amount.errors }}
    
    Submit button 
    <button type="submit">Save</button>
</form>

<script>
    // Populate form fields with data from Invoice object
    $(document).ready(function() {
        // Get values from Invoice object (replace 'invoiceData' with your actual object)
        var customerName = "{{ invoice.customer }}";
        var totalAmount = "{{ invoice.total_amount }}";
        var date = "{{ invoice.date }}";
        var balance = "{{ invoice.balance }}";
        
        // Assign values to form fields
        $('#id_customer_name').val(customerName);
        $('#id_total_amount').val(totalAmount);
        $('#id_date').val(date);
        $('#id_balance').val(balance);
    });
</script> -->
>>>>>>> origin/main